---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      hesias.io/application: database
  template:
    metadata:
      labels:
        hesias.io/application: database
        hesias.io/datacenter: clermont-ferrand
    spec:
      containers:
        - name: influxdb-container
          image: influxdb:1.8
          livenessProbe:
            httpGet:
              path: /health
              port: 8086
          readinessProbe:
            httpGet:
              path: /health
              port: 8086
          env:
            - name: INFLUXDB_DB
              value: mydatabase
            - name: INFLUXDB_USER
              value: influxuser
            - name: INFLUXDB_USER_PASSWORD
              value: influxpassword
            - name: INFLUXDB_ADMIN_USER
              value: admin
            - name: INFLUXDB_ADMIN_PASSWORD
              value: adminpassword
---
apiVersion: v1
kind: Service
metadata: 
  name: influxdb-service
spec:
  selector:
    hesias.io/application: database
  ports: 
    - name: influxdb-http
      port: 8086
      targetPort: 8086
      protocol: TCP
