apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      hesias.io/application: dashboard
  template:
    metadata:
      labels:
        hesias.io/application: dashboard
        hesias.io/datacenter: clermont-ferrand
    spec:
      containers:
        - name: grafana-container
          image: grafana/grafana
          ports:
            - containerPort: 3000
              name: grafana-http
