---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      hesias.io/application: database-prestashop
  template:
    metadata:
      labels:
        hesias.io/application: database-prestashop
        hesias.io/datacenter: clermont-ferrand
    spec:
      containers:
      - name: mariadb-container
        image: mariadb:10
        env:
          - name: MARIADB_ROOT_PASSWORD
            value: root
          - name: MARIADB_DATABASE
            value: prestashop
          - name: MARIADB_USER
            value: presta-user
          - name: MARIADB_PASSWORD
            value: presta-password
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mydata
      volumes:
        - name: mydata
          persistentVolumeClaim:
            claimName: mariadb-pvc

---
apiVersion: v1
kind: Service
metadata: 
  name: mariadb-service
spec:
  selector:
    hesias.io/application: database-prestashop
  ports: 
    - port: 3306
