---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prestashop-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      hesias.io/application: shop
  template:
    metadata:
      labels:
        hesias.io/application: shop
        hesias.io/datacenter: clermont-ferrand
    spec:
      containers:
      - name: prestashop-container
        image: prestashop/prestashop:1.7.8
        volumeMounts:
          - mountPath: /var/www/html
            name: web-data 
          - mountPath: /var/www/html/cache
            name: cache
          - mountPath: /var/www/html/var/cache
            name: var-cache
      volumes:
        - name: web-data
          persistentVolumeClaim:
            claimName: prestashop-pvc
        - name: cache
          emptyDir: 
            medium: Memory
            sizeLimit: 128Mi
        - name: var-cache
          emptyDir:
            medium: Memory
            sizeLimit: 128Mi
---
apiVersion: v1
kind: Service
metadata: 
  name: prestashop-service
spec:
  selector:
    hesias.io/application: shop
  type: LoadBalancer
  ports: 
  - port: 80
    targetPort: 80
