---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prestashop-pv
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteMany
  storageClassName: slow
  hostPath:
    path: /data/prestashop-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteMany
  storageClassName: speed
  hostPath:
    path: /data/mysql-pv

