apiVersion: apps/v1
kind: Deployment
metadata:
  name: meteo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      hesias.io/application: weather
  template:
    metadata:
      labels:
        hesias.io/application: weather
        hesias.io/datacenter: clermont-ferrand
    spec:
      containers:
        - name: meteo-container
          image: pockost/telegraf-cf-weather
          env:
            - name: "INFLUXDB_HOST"
              value: "influxdb-svc"
            - name: "INFLUXDB_PORT"
              value: "8086"
            - name: "INFLUXDB_NAME"
              valueFrom:
                secretKeyRef:
                  name: influxdb-secret
                  key: database-name
            - name: "INFLUXDB_USER"
              valueFrom:
                secretKeyRef:
                  name: influxdb-secret
                  key: username
            - name: "INFLUXDB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: influxdb-secret
                  key: password
